# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements. See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License. You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: CI

on:
  push:
    branches-ignore: [ 'dependabot/**' ]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test:
    name: Java ${{ matrix.java_version }}, Scala ${{ matrix.scala_version }}, ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        distribution: [ temurin ]
        java_version: [ 8, 11, 17 ]
        scala_version: [ 2.12.15 ]
        os: [ ubuntu-20.04 ]
    runs-on: ${{ matrix.os }}
    env:
      SBT: sbt -J-Xms1024m -J-Xmx5120m -J-XX:ReservedCodeCacheSize=512m -J-XX:MaxMetaspaceSize=1024m ++${{ matrix.scala_version }}

    steps:

      ############################################################
      # Setup
      ############################################################

      - name: Checkout Repository
        uses: actions/checkout@v2.4.0
        with:
          fetch-depth: 0

      - name: Install Java
        uses: actions/setup-java@v2.5.0
        with:
          distribution: ${{ matrix.distribution }}
          java-version: ${{ matrix.java_version }}

      ############################################################
      # Test
      ############################################################

      - name: Run Rat Check
        run: $SBT ratCheck

      - name: Run Tests
        run: $SBT test
